### ISSUE TITLE
Adding Shido Chain

### ISSUE THREAD

**Issue by ArunBabu98** [mrtnetwork/cosmos_sdk#1]
How do I add shido chain which is built using cosmos sdk using this library and derive addresses?

chainid = shido_9008-1

chain name= shido

New RPC URL = https://tendermint.shidoscan.com

New REST URL = https://swagger.shidoscan.com

Address Prefix= shido

Native Denom= SHIDO

Coin Type= 60

Decimals= 18

**Comment by mrtnetwork** [comment]
> How do I add shido chain which is built using cosmos sdk using this library and derive addresses?
> 
> chainid = shido_9008-1
> 
> chain name= shido
> 
> New RPC URL = https://tendermint.shidoscan.com
> 
> New REST URL = https://swagger.shidoscan.com
> 
> Address Prefix= shido
> 
> Native Denom= SHIDO
> 
> Coin Type= 60
> 
> Decimals= 18

Please try changing the provider RPC URL and use an address with the HRP (Human-Readable Part) 'shido' for the Shido native coin instead of 'uatom'. It might work. Give it a try and let me know.

**Comment by ArunBabu98** [comment]
` final seedBytes = Bip39SeedGenerator(Mnemonic.fromString(mnem)).generate();

    // /// Derive BIP44 path
    final bip44 =
        Bip44.fromSeed(seedBytes, Bip44Coins.cosmos).deriveDefaultPath;

    /// Create a Cosmos Secp256k1 private key from the derived private key bytes
    final privateKey =
        CosmosSecp256K1PrivateKey.fromBytes(bip44.privateKey.raw);

    /// Generate the corresponding public key and address for Secp256k1
    final pubkey =
        CosmosSecp256K1PublicKey.fromBytes(bip44.publicKey.compressed);
    final cosmosAddress = pubkey.toAddresss(hrp: "shido");`
    
    Do you mean like this?

**Comment by ArunBabu98** [comment]
```
` test('Shido-Address test', () async {
    /// Generate seed bytes from a mnemonic
    final seedBytes = Bip39SeedGenerator(Mnemonic.fromString(mnem)).generate();

    /// Derive BIP44 path
    final bip44 =
        Bip44.fromSeed(seedBytes, Bip44Coins.cosmos).deriveDefaultPath;

    /// Create a Cosmos Secp256k1 private key from the derived private key bytes
    final privateKey =
        CosmosSecp256K1PrivateKey.fromBytes(bip44.privateKey.raw);

    /// Generate the corresponding public key and address for Secp256k1
    final pubkey =
        CosmosSecp256K1PublicKey.fromBytes(bip44.publicKey.compressed);
    final cosmosAddress = pubkey.toAddresss(hrp: "shido");
    print("Result -> $cosmosAddress");
    print("Expected -> shido1z0dfszhq7vfcvrf3qqqgzqgemdq4dspsnxk43w");
  }); `
```

Is this what you mean? But the expected address and the result I'm getting is very different

**Comment by mrtnetwork** [comment]
> ```
> ` test('Shido-Address test', () async {
>     /// Generate seed bytes from a mnemonic
>     final seedBytes = Bip39SeedGenerator(Mnemonic.fromString(mnem)).generate();
> 
>     /// Derive BIP44 path
>     final bip44 =
>         Bip44.fromSeed(seedBytes, Bip44Coins.cosmos).deriveDefaultPath;
> 
>     /// Create a Cosmos Secp256k1 private key from the derived private key bytes
>     final privateKey =
>         CosmosSecp256K1PrivateKey.fromBytes(bip44.privateKey.raw);
> 
>     /// Generate the corresponding public key and address for Secp256k1
>     final pubkey =
>         CosmosSecp256K1PublicKey.fromBytes(bip44.publicKey.compressed);
>     final cosmosAddress = pubkey.toAddresss(hrp: "shido");
>     print("Result -> $cosmosAddress");
>     print("Expected -> shido1z0dfszhq7vfcvrf3qqqgzqgemdq4dspsnxk43w");
>   }); `
> ```
> 
> Is this what you mean? But the expected address and the result I'm getting is very different

oh sorry I think you want to interact with the chain, you should use the correct coin and derive with ```Bip32Slip10Secp256k1``` instead Bip44

try this if Shido uses Coin ID 60

```dart
  final slp10 = Bip32Slip10Secp256k1.fromSeed(seedBytes);
  final derive = slp10.derivePath("m/44'/60'/0'/0/0");
  final pubkey =
      CosmosSecp256K1PublicKey.fromBytes(derive.publicKey.compressed);
  final cosmosAddress = pubkey.toAddresss(hrp: "shido");
```

**Comment by ArunBabu98** [comment]
Instead of CosmosSecp256K1, the official document recommends eth_secp256k1. Does blockchain utils have this algo?

the private and public key derived is correct, but the address uses eth_secp256k1 this derivation algorithm


Adding the doc here for reference

[https://docs.shidoscan.com/protocol/concepts/accounts](https://docs.shidoscan.com/protocol/concepts/accounts)

**Comment by mrtnetwork** [comment]
> Instead of CosmosSecp256K1, the official document recommends eth_secp256k1. Does blockchain utils have this algo?
> 
> the private and public key derived is correct, but the address uses eth_secp256k1 this derivation algorithm
> 
> Adding the doc here for reference
> 
> https://docs.shidoscan.com/protocol/concepts/accounts

for eth address you can use 
```
 final ethAddress = EthAddrEncoder().encodeKey(pubkey.toBytes());
  print(ethAddress);
```
to see the address or show it to the user but if the transaction not working with the Bech32 address (you can check with testnet ) I try to implant it in the next update for cosmos SDK

**Comment by ArunBabu98** [comment]
Hi, I managed to implement the address.

I had to use eth_secp256k1 instead of the normal secp256k1 curve,

```
// Normal secp256k1
    List<int> sha256Hash = sha256.convert(publicKeyBytes).bytes;
    var digest = RIPEMD160Digest();
    // ETh secp256k1
    final uncompressedPublicKeyBytes =
        Uint8List.fromList(derive.publicKey.uncompressed);
    final keccakDigest =
        KeccakDigest(256).process(uncompressedPublicKeyBytes.sublist(1));
    final kdigest = keccakDigest.sublist(12, 32);
```

Then use the bech32 to encode the digest with HRP.

This will be useful for your library since some of the chains like shido, evmos etc use this. Thank you for your time.
